version: '3.9'
services:
  app:
    build: .
    expose:
      - 4567
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '0.1'
          memory: 90M
        limits:
          cpus: '0.33'
          memory: 128M
    networks:
      - app-network
  nginx:
    image: nginx:1.21.3
    container_name: nginx
    deploy:
      resources:
        reservations:
          memory: 8M
        limits:
          memory: 16M
    ports:
      - "3040:3040"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx/certs/privkey.pem:/etc/nginx/privkey.pem
    depends_on:
      - app
    networks:
      - app-network
  redis:
    image: redis:6.2.6
    container_name: redis
    deploy:
      resources:
        reservations:
          memory: 8M
        limits:
          memory: 16M
    networks:
      - app-network
networks:
  app-network:
    driver: bridge