version: '3.9'

services:
  app:
    build: .
    expose:
      - 4567
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '0.1'
          memory: 90M
        limits:
          cpus: '0.33'
          memory: 128M
    networks:
      - app-network
 
  nginx:
    image: nginx:1.21.3
    container_name: nginx
    deploy:
      resources:
        reservations:
          memory: 8M
        limits:
          memory: 16M
    ports:
      - "3040:3040"
    volumes:
      - ./docker-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./docker-volumes/nginx/certs/fullchain.pem:/etc/nginx/fullchain.pem
    #   - ./docker-volumes/nginx/certs/privkey.pem:/etc/nginx/privkey.pem
    depends_on:
      - app
    networks:
      - app-network
 
  redis:
    image: redis:6.2.6
    container_name: redis
    deploy:
      resources:
        reservations:
          memory: 8M
        limits:
          memory: 16M
    ports:
      - "6379:6379"
    networks:
      - app-network
 
  database:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: app_sys
      POSTGRES_PASSWORD: code@@2
      POSTGRES_DB: code
    ports:
      - "5432:5432"
    deploy:
      resources:
        reservations:
          memory: 32M
        limits:
          memory: 64M
    networks:
      - app-network
    volumes:
      - ./docker-volumes/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: