version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    deploy:
      resources:
        reservations:
          memory: 8M
        limits:
          memory: 16M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt
      - /etc/nginx/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key
    depends_on:
      - app

  app:
    build: .
    expose:
      - 4567
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '0.1'
          memory: 90M
        limits:
          cpus: '0.33'
          memory: 128M

  redis:
    image: redis:latest
    container_name: redis
    deploy:
      resources:
        reservations:
          memory: 8M
        limits:
          memory: 16M