default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: app_sys
  password: code@@2
  port: 5432

development:
  <<: *default
  database: code
  host: database  # Use o nome do serviço do banco de dados

test:
  <<: *default
  database: code
  host: database  # Use o nome do serviço do banco de dados

production:
  <<: *default
  database: code
  username: app_sys
  password: code@@2
  host: database  # Use o nome do serviço do banco de dados