default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: app_sys
  password: code@@2
  host: database
  
development:
  <<: *default
  database: code

production:
  <<: *default
  database: code
