default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: app_sys
  password: code@@2
  port: 5432
  host: localhost
  
development:
  <<: *default
  database: code

test:
  <<: *default
  database: code

production:
  <<: *default
  database: code
  username: app_sys
  password: code@@2
