default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: app_sys
  password: code@@2
  host: localhost
  port: 5432

development:
  <<: *default
  database: code

test:
  <<: *default
  database: code

production:
  <<: *default
  database: code
  username: app_sys
  password: code@@2